# ===== TODO-01: Cau hinh Data Source =====
spring.application.name=A2Khoi_sba301
server.port=8080

# Doi databaseName / username / password theo may cua ban
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=A2Khoi_sba301;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
# update: tu tao bang tu Entity neu chua co (Use Spring Data JPA to create the database)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true